package com.books.bookroom.model;
// Generated 19 Sep, 2020 2:32:54 PM by Hibernate Tools 5.2.12.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * BookDetail generated by hbm2java
 */
@Entity
@Table(name = "book_detail", catalog = "bookroom", uniqueConstraints = @UniqueConstraint(columnNames = "Edition_ID"))
public class BookDetail implements java.io.Serializable {

	private int bookId;
	private BookTitle bookTitle;
	private String bookName;
	private String author;
	private String publisher;
	private String category;
	private String subCategory;
	private String subject;
	private String genre;
	private String bookEdition;
	private Float price;
	private Date dateOfPublication;
	private int editionId;

	public BookDetail() {
	}

	public BookDetail(int bookId, BookTitle bookTitle, String bookName, String category, String subCategory,
			int editionId) {
		this.bookId = bookId;
		this.bookTitle = bookTitle;
		this.bookName = bookName;
		this.category = category;
		this.subCategory = subCategory;
		this.editionId = editionId;
	}

	public BookDetail(int bookId, BookTitle bookTitle, String bookName, String author, String publisher,
			String category, String subCategory, String subject, String genre, String bookEdition, Float price,
			Date dateOfPublication, int editionId) {
		this.bookId = bookId;
		this.bookTitle = bookTitle;
		this.bookName = bookName;
		this.author = author;
		this.publisher = publisher;
		this.category = category;
		this.subCategory = subCategory;
		this.subject = subject;
		this.genre = genre;
		this.bookEdition = bookEdition;
		this.price = price;
		this.dateOfPublication = dateOfPublication;
		this.editionId = editionId;
	}

	@Id

	@Column(name = "Book_ID", unique = true, nullable = false)
	public int getBookId() {
		return this.bookId;
	}

	public void setBookId(int bookId) {
		this.bookId = bookId;
	}

//	@ManyToOne(fetch = FetchType.LAZY)
//	@JoinColumn(name = "Title_ID", nullable = false)
//	public BookTitle getBookTitle() {
//		return this.bookTitle;
//	}
//
//	public void setBookTitle(BookTitle bookTitle) {
//		this.bookTitle = bookTitle;
//	}

	@Column(name = "BookName", nullable = false, length = 100)
	public String getBookName() {
		return this.bookName;
	}

	public void setBookName(String bookName) {
		this.bookName = bookName;
	}

	@Column(name = "Author", length = 100)
	public String getAuthor() {
		return this.author;
	}

	public void setAuthor(String author) {
		this.author = author;
	}

	@Column(name = "Publisher", length = 100)
	public String getPublisher() {
		return this.publisher;
	}

	public void setPublisher(String publisher) {
		this.publisher = publisher;
	}

	@Column(name = "Category", nullable = false, length = 45)
	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	@Column(name = "SubCategory", nullable = false, length = 45)
	public String getSubCategory() {
		return this.subCategory;
	}

	public void setSubCategory(String subCategory) {
		this.subCategory = subCategory;
	}

	@Column(name = "Subject", length = 45)
	public String getSubject() {
		return this.subject;
	}

	public void setSubject(String subject) {
		this.subject = subject;
	}

	@Column(name = "Genre", length = 45)
	public String getGenre() {
		return this.genre;
	}

	public void setGenre(String genre) {
		this.genre = genre;
	}

	@Column(name = "BookEdition", length = 45)
	public String getBookEdition() {
		return this.bookEdition;
	}

	public void setBookEdition(String bookEdition) {
		this.bookEdition = bookEdition;
	}

	@Column(name = "Price", precision = 12, scale = 0)
	public Float getPrice() {
		return this.price;
	}

	public void setPrice(Float price) {
		this.price = price;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DateOfPublication", length = 10)
	public Date getDateOfPublication() {
		return this.dateOfPublication;
	}

	public void setDateOfPublication(Date dateOfPublication) {
		this.dateOfPublication = dateOfPublication;
	}

	@Column(name = "Edition_ID", unique = true, nullable = false)
	public int getEditionId() {
		return this.editionId;
	}

	public void setEditionId(int editionId) {
		this.editionId = editionId;
	}

}
