 package com.books.bookroom.model;
// Generated 15 Sep, 2020 4:34:00 PM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * BookTitle generated by hbm2java
 */
@Entity
@Table(name = "book_title", catalog = "bookroom")
public class BookTitle implements java.io.Serializable {

	private int titleId;
	private String isbnNumber;
	private String bookName;
	private String author;
	private String publisher;
	private String category;
	private String subCategory;
	private String subject;
	private String genre;
	private String isForSection1;
	private String isForSection2;
	private String isForSection3;
	private String isForSection4;
	private String noOfCopies;

	public BookTitle() {
	}

	public BookTitle(int titleId) {
		this.titleId = titleId;
	}

	public BookTitle(int titleId, String isbnNumber, String bookName, String author, String publisher, String category,
			String subCategory, String subject, String genre, String isForSection1, String isForSection2,
			String isForSection3, String isForSection4, String noOfCopies) {
		this.titleId = titleId;
		this.isbnNumber = isbnNumber;
		this.bookName = bookName;
		this.author = author;
		this.publisher = publisher;
		this.category = category;
		this.subCategory = subCategory;
		this.subject = subject;
		this.genre = genre;
		this.isForSection1 = isForSection1;
		this.isForSection2 = isForSection2;
		this.isForSection3 = isForSection3;
		this.isForSection4 = isForSection4;
		this.noOfCopies = noOfCopies;
	}

	@Id

	@Column(name = "TitleID", unique = true, nullable = false)
	public int getTitleId() {
		return this.titleId;
	}

	public void setTitleId(int titleId) {
		this.titleId = titleId;
	}

	@Column(name = "ISBN_Number", length = 45)
	public String getIsbnNumber() {
		return this.isbnNumber;
	}

	public void setIsbnNumber(String isbnNumber) {
		this.isbnNumber = isbnNumber;
	}

	@Column(name = "BookName", length = 45)
	public String getBookName() {
		return this.bookName;
	}

	public void setBookName(String bookName) {
		this.bookName = bookName;
	}

	@Column(name = "Author", length = 45)
	public String getAuthor() {
		return this.author;
	}

	public void setAuthor(String author) {
		this.author = author;
	}

	@Column(name = "Publisher", length = 45)
	public String getPublisher() {
		return this.publisher;
	}

	public void setPublisher(String publisher) {
		this.publisher = publisher;
	}

	@Column(name = "Category", length = 45)
	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	@Column(name = "Sub_Category", length = 45)
	public String getSubCategory() {
		return this.subCategory;
	}

	public void setSubCategory(String subCategory) {
		this.subCategory = subCategory;
	}

	@Column(name = "Subject", length = 45)
	public String getSubject() {
		return this.subject;
	}

	public void setSubject(String subject) {
		this.subject = subject;
	}

	@Column(name = "Genre", length = 45)
	public String getGenre() {
		return this.genre;
	}

	public void setGenre(String genre) {
		this.genre = genre;
	}

	@Column(name = "isForSection1", length = 45)
	public String getIsForSection1() {
		return this.isForSection1;
	}

	public void setIsForSection1(String isForSection1) {
		this.isForSection1 = isForSection1;
	}

	@Column(name = "isForSection2", length = 45)
	public String getIsForSection2() {
		return this.isForSection2;
	}

	public void setIsForSection2(String isForSection2) {
		this.isForSection2 = isForSection2;
	}

	@Column(name = "isForSection3", length = 45)
	public String getIsForSection3() {
		return this.isForSection3;
	}

	public void setIsForSection3(String isForSection3) {
		this.isForSection3 = isForSection3;
	}

	@Column(name = "isForSection4", length = 45)
	public String getIsForSection4() {
		return this.isForSection4;
	}

	public void setIsForSection4(String isForSection4) {
		this.isForSection4 = isForSection4;
	}

	@Column(name = "NoOfCopies", length = 45)
	public String getNoOfCopies() {
		return this.noOfCopies;
	}

	public void setNoOfCopies(String noOfCopies) {
		this.noOfCopies = noOfCopies;
	}

}
