package com.books.bookroom.model;
// Generated 19 Sep, 2020 2:32:54 PM by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * BookTitle generated by hbm2java
 */
@Entity
@Table(name = "book_title", catalog = "bookroom")
public class BookTitle implements java.io.Serializable {

	private int titleId;
	private String isbnNumber;
	private String bookName;
	private String author;
	private String publisher;
	private String category;
	private String subCategory;
	private String subject;
	private String genre;
	private Byte isForSection1;
	private Byte isForSection2;
	private Byte isForSection3;
	private Byte isForSection4;
	private Integer noOfCopies;
	private Set bookDetails = new HashSet(0);

	public BookTitle() {
	}

	public BookTitle(int titleId, String bookName) {
		this.titleId = titleId;
		this.bookName = bookName;
	}

	public BookTitle(int titleId, String isbnNumber, String bookName, String author, String publisher, String category,
			String subCategory, String subject, String genre, Byte isForSection1, Byte isForSection2,
			Byte isForSection3, Byte isForSection4, Integer noOfCopies, Set bookDetails) {
		this.titleId = titleId;
		this.isbnNumber = isbnNumber;
		this.bookName = bookName;
		this.author = author;
		this.publisher = publisher;
		this.category = category;
		this.subCategory = subCategory;
		this.subject = subject;
		this.genre = genre;
		this.isForSection1 = isForSection1;
		this.isForSection2 = isForSection2;
		this.isForSection3 = isForSection3;
		this.isForSection4 = isForSection4;
		this.noOfCopies = noOfCopies;
		this.bookDetails = bookDetails;
	}

	@Id

	@Column(name = "TitleID", unique = true, nullable = false)
	public int getTitleId() {
		return this.titleId;
	}

	public void setTitleId(int titleId) {
		this.titleId = titleId;
	}

	@Column(name = "ISBN_Number", length = 45)
	public String getIsbnNumber() {
		return this.isbnNumber;
	}

	public void setIsbnNumber(String isbnNumber) {
		this.isbnNumber = isbnNumber;
	}

	@Column(name = "BookName", nullable = false, length = 100)
	public String getBookName() {
		return this.bookName;
	}

	public void setBookName(String bookName) {
		this.bookName = bookName;
	}

	@Column(name = "Author", length = 100)
	public String getAuthor() {
		return this.author;
	}

	public void setAuthor(String author) {
		this.author = author;
	}

	@Column(name = "Publisher", length = 100)
	public String getPublisher() {
		return this.publisher;
	}

	public void setPublisher(String publisher) {
		this.publisher = publisher;
	}

	@Column(name = "Category", length = 100)
	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	@Column(name = "Sub_Category", length = 50)
	public String getSubCategory() {
		return this.subCategory;
	}

	public void setSubCategory(String subCategory) {
		this.subCategory = subCategory;
	}

	@Column(name = "Subject", length = 50)
	public String getSubject() {
		return this.subject;
	}

	public void setSubject(String subject) {
		this.subject = subject;
	}

	@Column(name = "Genre", length = 45)
	public String getGenre() {
		return this.genre;
	}

	public void setGenre(String genre) {
		this.genre = genre;
	}

	@Column(name = "isForSection1")
	public Byte getIsForSection1() {
		return this.isForSection1;
	}

	public void setIsForSection1(Byte isForSection1) {
		this.isForSection1 = isForSection1;
	}

	@Column(name = "isForSection2")
	public Byte getIsForSection2() {
		return this.isForSection2;
	}

	public void setIsForSection2(Byte isForSection2) {
		this.isForSection2 = isForSection2;
	}

	@Column(name = "isForSection3")
	public Byte getIsForSection3() {
		return this.isForSection3;
	}

	public void setIsForSection3(Byte isForSection3) {
		this.isForSection3 = isForSection3;
	}

	@Column(name = "isForSection4")
	public Byte getIsForSection4() {
		return this.isForSection4;
	}

	public void setIsForSection4(Byte isForSection4) {
		this.isForSection4 = isForSection4;
	}

	@Column(name = "NoOfCopies")
	public Integer getNoOfCopies() {
		return this.noOfCopies;
	}

	public void setNoOfCopies(Integer noOfCopies) {
		this.noOfCopies = noOfCopies;
	}

//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "bookTitle")
//	public Set getBookDetails() {
//		return this.bookDetails;
//	}
//
//	public void setBookDetails(Set bookDetails) {
//		this.bookDetails = bookDetails;
//	}

}
