package com.books.bookroom.model;
// Generated 15 Sep, 2020 4:34:00 PM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * IssueDetails generated by hbm2java
 */
@Entity
@Table(name = "issue_details", catalog = "bookroom")
public class IssueDetails implements java.io.Serializable {

	private int issueId;
	private String bookId;
	private String userId;
	private String dateOfIssue;
	private String targetReturnDate;
	private String allowedIssuingPeriod;
	private String actualReturnDate;
	private String occupancyPeriod;
	private String lateFeeCharged;
	private String concessionOffered;
	private String isIssued;

	public IssueDetails() {
	}

	public IssueDetails(int issueId) {
		this.issueId = issueId;
	}

	public IssueDetails(int issueId, String bookId, String userId, String dateOfIssue, String targetReturnDate,
			String allowedIssuingPeriod, String actualReturnDate, String occupancyPeriod, String lateFeeCharged,
			String concessionOffered, String isIssued) {
		this.issueId = issueId;
		this.bookId = bookId;
		this.userId = userId;
		this.dateOfIssue = dateOfIssue;
		this.targetReturnDate = targetReturnDate;
		this.allowedIssuingPeriod = allowedIssuingPeriod;
		this.actualReturnDate = actualReturnDate;
		this.occupancyPeriod = occupancyPeriod;
		this.lateFeeCharged = lateFeeCharged;
		this.concessionOffered = concessionOffered;
		this.isIssued = isIssued;
	}

	@Id

	@Column(name = "Issue_ID", unique = true, nullable = false)
	public int getIssueId() {
		return this.issueId;
	}

	public void setIssueId(int issueId) {
		this.issueId = issueId;
	}

	@Column(name = "Book_ID", length = 45)
	public String getBookId() {
		return this.bookId;
	}

	public void setBookId(String bookId) {
		this.bookId = bookId;
	}

	@Column(name = "User_ID", length = 45)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "DateOfIssue", length = 45)
	public String getDateOfIssue() {
		return this.dateOfIssue;
	}

	public void setDateOfIssue(String dateOfIssue) {
		this.dateOfIssue = dateOfIssue;
	}

	@Column(name = "TargetReturnDate", length = 45)
	public String getTargetReturnDate() {
		return this.targetReturnDate;
	}

	public void setTargetReturnDate(String targetReturnDate) {
		this.targetReturnDate = targetReturnDate;
	}

	@Column(name = "AllowedIssuingPeriod", length = 45)
	public String getAllowedIssuingPeriod() {
		return this.allowedIssuingPeriod;
	}

	public void setAllowedIssuingPeriod(String allowedIssuingPeriod) {
		this.allowedIssuingPeriod = allowedIssuingPeriod;
	}

	@Column(name = "ActualReturnDate", length = 45)
	public String getActualReturnDate() {
		return this.actualReturnDate;
	}

	public void setActualReturnDate(String actualReturnDate) {
		this.actualReturnDate = actualReturnDate;
	}

	@Column(name = "OccupancyPeriod", length = 45)
	public String getOccupancyPeriod() {
		return this.occupancyPeriod;
	}

	public void setOccupancyPeriod(String occupancyPeriod) {
		this.occupancyPeriod = occupancyPeriod;
	}

	@Column(name = "LateFeeCharged", length = 45)
	public String getLateFeeCharged() {
		return this.lateFeeCharged;
	}

	public void setLateFeeCharged(String lateFeeCharged) {
		this.lateFeeCharged = lateFeeCharged;
	}

	@Column(name = "ConcessionOffered", length = 45)
	public String getConcessionOffered() {
		return this.concessionOffered;
	}

	public void setConcessionOffered(String concessionOffered) {
		this.concessionOffered = concessionOffered;
	}

	@Column(name = "isIssued", length = 45)
	public String getIsIssued() {
		return this.isIssued;
	}

	public void setIsIssued(String isIssued) {
		this.isIssued = isIssued;
	}

}
