package com.books.bookroom.model;
// Generated 19 Sep, 2020 2:32:54 PM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PlanDetails generated by hbm2java
 */
@Entity
@Table(name = "plan_details", catalog = "bookroom")
public class PlanDetails implements java.io.Serializable {

	private int planId;
	private String amount;
	private String validity;
	private String benefits;

	public PlanDetails() {
	}

	public PlanDetails(int planId) {
		this.planId = planId;
	}

	public PlanDetails(int planId, String amount, String validity, String benefits) {
		this.planId = planId;
		this.amount = amount;
		this.validity = validity;
		this.benefits = benefits;
	}

	@Id

	@Column(name = "Plan_ID", unique = true, nullable = false)
	public int getPlanId() {
		return this.planId;
	}

	public void setPlanId(int planId) {
		this.planId = planId;
	}

	@Column(name = "Amount", length = 45)
	public String getAmount() {
		return this.amount;
	}

	public void setAmount(String amount) {
		this.amount = amount;
	}

	@Column(name = "Validity", length = 45)
	public String getValidity() {
		return this.validity;
	}

	public void setValidity(String validity) {
		this.validity = validity;
	}

	@Column(name = "Benefits", length = 45)
	public String getBenefits() {
		return this.benefits;
	}

	public void setBenefits(String benefits) {
		this.benefits = benefits;
	}

}
