package com.books.bookroom.model;
// Generated 19 Sep, 2020 2:32:54 PM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * UserMembership generated by hbm2java
 */
@Entity
@Table(name = "user_membership", catalog = "bookroom")
public class UserMembership implements java.io.Serializable {

	private int userPlanRefId;
	private String userId;
	private String planId;
	private String amount;
	private String purchaseDate;
	private String validity;
	private String expiryDate;
	private String benefits;
	private String possesionOfBooks;

	public UserMembership() {
	}

	public UserMembership(int userPlanRefId) {
		this.userPlanRefId = userPlanRefId;
	}

	public UserMembership(int userPlanRefId, String userId, String planId, String amount, String purchaseDate,
			String validity, String expiryDate, String benefits, String possesionOfBooks) {
		this.userPlanRefId = userPlanRefId;
		this.userId = userId;
		this.planId = planId;
		this.amount = amount;
		this.purchaseDate = purchaseDate;
		this.validity = validity;
		this.expiryDate = expiryDate;
		this.benefits = benefits;
		this.possesionOfBooks = possesionOfBooks;
	}

	@Id

	@Column(name = "User_Plan_Ref_ID", unique = true, nullable = false)
	public int getUserPlanRefId() {
		return this.userPlanRefId;
	}

	public void setUserPlanRefId(int userPlanRefId) {
		this.userPlanRefId = userPlanRefId;
	}

	@Column(name = "User_ID", length = 45)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "Plan_ID", length = 45)
	public String getPlanId() {
		return this.planId;
	}

	public void setPlanId(String planId) {
		this.planId = planId;
	}

	@Column(name = "Amount", length = 45)
	public String getAmount() {
		return this.amount;
	}

	public void setAmount(String amount) {
		this.amount = amount;
	}

	@Column(name = "Purchase_Date", length = 45)
	public String getPurchaseDate() {
		return this.purchaseDate;
	}

	public void setPurchaseDate(String purchaseDate) {
		this.purchaseDate = purchaseDate;
	}

	@Column(name = "Validity", length = 45)
	public String getValidity() {
		return this.validity;
	}

	public void setValidity(String validity) {
		this.validity = validity;
	}

	@Column(name = "Expiry_Date", length = 45)
	public String getExpiryDate() {
		return this.expiryDate;
	}

	public void setExpiryDate(String expiryDate) {
		this.expiryDate = expiryDate;
	}

	@Column(name = "Benefits", length = 45)
	public String getBenefits() {
		return this.benefits;
	}

	public void setBenefits(String benefits) {
		this.benefits = benefits;
	}

	@Column(name = "PossesionOfBooks", length = 45)
	public String getPossesionOfBooks() {
		return this.possesionOfBooks;
	}

	public void setPossesionOfBooks(String possesionOfBooks) {
		this.possesionOfBooks = possesionOfBooks;
	}

}
