package com.books.bookroom.model;
// Generated 19 Sep, 2020 2:32:54 PM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * UserAddress generated by hbm2java
 */
@Entity
@Table(name = "user_address", catalog = "bookroom")
public class UserAddress implements java.io.Serializable {

	private int addressRefId;
	private String addressType;
	private String isActive;
	private String userId;
	private String addressLine1;
	private String addressLine2;
	private String addressLine3;
	private String addressLine4;
	private String city;
	private String pinCode;
	private String state;

	public UserAddress() {
	}

	public UserAddress(int addressRefId) {
		this.addressRefId = addressRefId;
	}

	public UserAddress(int addressRefId, String addressType, String isActive, String userId, String addressLine1,
			String addressLine2, String addressLine3, String addressLine4, String city, String pinCode, String state) {
		this.addressRefId = addressRefId;
		this.addressType = addressType;
		this.isActive = isActive;
		this.userId = userId;
		this.addressLine1 = addressLine1;
		this.addressLine2 = addressLine2;
		this.addressLine3 = addressLine3;
		this.addressLine4 = addressLine4;
		this.city = city;
		this.pinCode = pinCode;
		this.state = state;
	}

	@Id

	@Column(name = "Address_Ref_ID", unique = true, nullable = false)
	public int getAddressRefId() {
		return this.addressRefId;
	}

	public void setAddressRefId(int addressRefId) {
		this.addressRefId = addressRefId;
	}

	@Column(name = "AddressType", length = 45)
	public String getAddressType() {
		return this.addressType;
	}

	public void setAddressType(String addressType) {
		this.addressType = addressType;
	}

	@Column(name = "isActive", length = 45)
	public String getIsActive() {
		return this.isActive;
	}

	public void setIsActive(String isActive) {
		this.isActive = isActive;
	}

	@Column(name = "UserID", length = 45)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "AddressLine1", length = 45)
	public String getAddressLine1() {
		return this.addressLine1;
	}

	public void setAddressLine1(String addressLine1) {
		this.addressLine1 = addressLine1;
	}

	@Column(name = "AddressLine2", length = 45)
	public String getAddressLine2() {
		return this.addressLine2;
	}

	public void setAddressLine2(String addressLine2) {
		this.addressLine2 = addressLine2;
	}

	@Column(name = "AddressLine3", length = 45)
	public String getAddressLine3() {
		return this.addressLine3;
	}

	public void setAddressLine3(String addressLine3) {
		this.addressLine3 = addressLine3;
	}

	@Column(name = "AddressLine4", length = 45)
	public String getAddressLine4() {
		return this.addressLine4;
	}

	public void setAddressLine4(String addressLine4) {
		this.addressLine4 = addressLine4;
	}

	@Column(name = "City", length = 45)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "PinCode", length = 45)
	public String getPinCode() {
		return this.pinCode;
	}

	public void setPinCode(String pinCode) {
		this.pinCode = pinCode;
	}

	@Column(name = "State", length = 45)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

}
